### ISSUE TITLE
A way to monitor mic input level and set a threshold on it ?

### ISSUE THREAD

**Issue by glaurent** [vadymmarkov/Tuner#25]
Hi,

Trying the Guitar Tuner example, I find that it detects pitches just out of the base level of noise that the microphone gets. So I'm looking for a way to "filter out" low level signals so that detection would only occur if the input level is above a certain value. I don't know much about AVAudio yet, so I'm asking if you have an idea on how to do this (or are planning to do it) before I dive into docs :)

Thanks

**Comment by glaurent** [comment]
I could implement this feature for the InputSignalTracker but not the OutputSignalTracker. I've tried submitted a pull request but apparently I don't have permission.

**Comment by vadymmarkov** [comment]
Hi @glaurent! Thanks for reaching out. Would love to look at your implementation of this feature. You can make a fork of the repo and then you'll be able to submit a PR here.

**Comment by glaurent** [comment]
Pull-request made :) thanks.

**Comment by vadymmarkov** [comment]
Fixed by https://github.com/vadymmarkov/Beethoven/pull/26
