### ISSUE TITLE
Swift 3 version ?

### ISSUE THREAD

**Issue by glaurent** [vadymmarkov/Tuner#34]
Just for information, is there a Swift 3 version in the works ? If not I might go ahead and try converting it...

**Comment by vadymmarkov** [comment]
@glaurent I haven't started yet. Have a lot of repos to migrate at the moment. But would be awesome if you can help 👍

**Comment by glaurent** [comment]
Actually, check your pullreqs, I did the conversions a few days ago for Beethoven and Pitchy ☺️.

**Comment by PCrompton** [comment]
@glaurent, is your Swift 3 version fully functional? Is it possible for me to use your version before the pull request is made?

**Comment by glaurent** [comment]
@PCrompton yes it is. The pull request is made, I assume you mean you want to use it before the pull request is integrated ? In which case you can simply use my fork of the repository. You'll also have to use my fork of Pitchy as well, so it will require a bit of setup but its doable.

**Comment by PCrompton** [comment]
I meant before it's integrated. You'll have to forgive my terminology, I'm new to the world of software development. I tried it but I keep getting one error or another. I may just have to wait until it's available on Cocoa Pods.

**Comment by glaurent** [comment]
If you're new to dev, then it's much better to wait for @vadymmarkov to integrate my pull requests, otherwise you'll just waste time fighting Cocoapods and Xcode project configuration.

**Comment by PCrompton** [comment]
Ok thanks. I see @vadymmarkov integrated Pitchy a few minutes so hopefully Beethoven won't be far behind. I should have waited to update to Xcode 8, but since I had already updated my iPhone to iOS 10 I couldn't build anything to it with Xcode 7. Is there any way to run Xcode 7 alongside Xcode 8? I tried to get my Xcode 7 back via Time Machine but the restore always fails.

**Comment by glaurent** [comment]
I think you can still download Xcode 7 here : https://developer.apple.com/download/more/

but better just wait for @vadymmarkov to integrate the other pullreq and just go with that and Xcode 8.

**Comment by vadymmarkov** [comment]
@PCrompton Or you can use https://github.com/KrauseFx/xcode-install to manage Xcode versions.

**Comment by vadymmarkov** [comment]
PR's are merged, but I'm having issues with my Xcode installations atm. Will release a new version to CocoaPods a bit later today. Sorry for delay.

**Comment by PCrompton** [comment]
@glaurent @vadymmarkov Thanks for your help! I'm doing the iOS Nanodegree at Udacity.com right now and I'm thinking of using Beethoven in my capstone project. I'll share the result with you when it's done if I do end up using it.

Also, do either of you recommend any open source libraries for displaying music notation?

**Comment by PCrompton** [comment]
@vadymmarkov will it work now with Carthage?

**Comment by glaurent** [comment]
@PCrompton I don't know any, sorry. To be honest, displaying music notation is pretty hard to do right. I used to work on Rosegarden (a Linux-based music editor and sequencer), so I have a bit of experience on this... Unless you really have to do it, it's something you'd better avoid.

**Comment by PCrompton** [comment]
@glaurent My app is a music reading learning app that will display a note and "listen" for the user to play the correct pitch on his/her instrument, so I might just find/create images instead.

**Comment by vadymmarkov** [comment]
@glaurent @PCrompton Status update: I've created new versions of Beethoven and Pitchy on GitHub, so you can use it with Carthage. As for CocoaPods, I'm not able to push a new release, seems like related to https://github.com/CocoaPods/CocoaPods/issues/5880

**Comment by PCrompton** [comment]
Thanks a lot!

**Comment by glaurent** [comment]
@vadymmarkov thanks, I'll probably switch to Carthage, simpler than Cocoapods. I've run into the same problem as you trying to update a pod of my own.

**Comment by glaurent** [comment]
I think we can close this one ?

**Comment by vadymmarkov** [comment]
@glaurent 👍
