### ISSUE TITLE
Swift 3.0 support for Example

### ISSUE THREAD

**Issue by ndduy** [vadymmarkov/Tuner#36]
Hey man,

Great library, I'm looking forward to use it however it looks like there is a discrepancy between the library and the example that you put in.

Can you put in the fix for that.

Thanks.

**Comment by glaurent** [comment]
I have a fix for that pending but it will be in an unrelated pull request. For now, you can use my fork, the YINalgorithm branch.

**Comment by vadymmarkov** [comment]
@ndduy Example is updated in the last release.
