### ISSUE TITLE
Requires `start` twice

### ISSUE THREAD

**Issue by orkenstein** [vadymmarkov/Tuner#45]
By some reason mic recognition start only when `start` called twice:
```
class ProcessingUnit: NSObject {
  
  var pitchChangedHandler: ((String) -> ())?
  
  let pitchEngine: PitchEngine = {
    let config = Config()
    let engine = PitchEngine(config: config, delegate: nil)
    return engine
  }()
		
  override init() {
    super.init()
    pitchEngine.delegate = self
    pitchEngine.start()
    pitchEngine.start()
  }

}

extension ProcessingUnit: PitchEngineDelegate {
  
  func pitchEngineDidReceiveError(_ pitchEngine: PitchEngine, error: Error) {
    
  }
  
  func pitchEngineWentBelowLevelThreshold(_ pitchEngine: PitchEngine) {
    
  }
  
  func pitchEngineDidReceivePitch(_ pitchEngine: PitchEngine, pitch: Pitch) {
    let value = pitch.note.letter.rawValue + "\(pitch.note.octave)"
    pitchChangedHandler?(value)
  }
}
```

**Comment by vadymmarkov** [comment]
@orkenstein Did you get a system popup asking for microphone permissions? Or maybe if you try to print an error in `pitchEngineDidReceiveError` delegate method it will put some light on this.

**Comment by orkenstein** [comment]
Yep, it asked for the permission.
No error from delegate.
These same thing for the example app: it works when you tap start for the second time.

**Comment by holeg** [comment]
Same happens to me. Only works when calling start 2 times.

**Comment by makuearth** [comment]
Same here. However, a usleep of 3 seconds after initialising and prior to calling start also solves the problem as well.

**Comment by thbwd** [comment]
Sometimes calling start simply doesn’t seem to have any effect. Any news on this?

**Comment by DebanjanChakrabortyCN** [comment]
Same here. I initialzed the AudioEngine, added the config, but the delegates never get called, even though I've added pitchEngine.start()

**Comment by austinchandra** [comment]
This happens to me as well, and with one additional issue.
When I call pitchEngine.start() twice (to get it to start at all), the app crashes sometimes when I call pitchEngine.stop().

Any way to fix this?

**Comment by vadymmarkov** [comment]
Hi @anandchandra50, I'm not sure why this happens, but I'll try to test and find out the problem when I get some time.

**Comment by makuearth** [comment]
I fixed the problem by inverting the initialization calls in InputSignalTracker.swift. On line 71 the code now reads 

    try audioEngine?.start()
    captureSession.startRunning()
    guard captureSession.isRunning == true else {
        throw InputSignalTrackerError.inputNodeMissing
    }

Note that audioEngine?.prepare() is not needed as it is called by audioEngine?.start(). 

Hope this helps. 

Anyhow, a big THANKS to vadymmarkov for this implementation!!!!

Has anyone some input on how to make YIN more robust with respect to to the transients during note attack and pitch changes?

**Comment by vadymmarkov** [comment]
That's great @makuearth! Would be awesome if you could make a PR with your fix.

**Comment by vadymmarkov** [comment]
@anandchandra50 I merged https://github.com/vadymmarkov/Beethoven/pull/55. Could you test the framework from `master` to verify that it's fixed now?

**Comment by austinchandra** [comment]
@vadymmarkov I implemented makuearth's change -- if that's the only difference, then it is fixed.

**Comment by makuearth** [comment]
Glad to hear that it worked. I made a PR in a fork.

Cheers,
Martin

**Comment by vadymmarkov** [comment]
Awesome, then I'm closing this issue. Thanks @makuearth

**Comment by austinchandra** [comment]
Going back to makuearth's point, though, is there any way to make YIN more accurate when pitch changes?
