### ISSUE TITLE
Beethoven crashes sometimes when stopping PitchEngine

### ISSUE THREAD

**Issue by austinchandra** [vadymmarkov/Tuner#54]
First of all, great library -- it's really helpful.
One problem is puzzling me right now:

<img width="856" alt="screen shot 2017-12-24 at 7 32 57 pm" src="https://user-images.githubusercontent.com/11379797/34332073-8cc25930-e8e1-11e7-8157-53b27fe56613.png">

I get this error sometimes (NOT ALWAYS) when I try to stop the pitch engine, which leads me to think it's some sort of memory issue.

The offending code:

<img width="816" alt="screen shot 2017-12-24 at 7 32 06 pm" src="https://user-images.githubusercontent.com/11379797/34332106-d0d52ac6-e8e1-11e7-8b35-09463966481c.png">

Any advice regarding this (especially if the problem's on my end) would be appreciated!

**Comment by austinchandra** [comment]
Still getting this issue. 

<img width="926" alt="screen shot 2017-12-30 at 6 30 33 pm" src="https://user-images.githubusercontent.com/11379797/34458660-92a03040-ed8f-11e7-91ae-bb4a0dd05b96.png">

Any ideas/ways to fix this? Seems like a problem in Beethoven, not on my side.

**Comment by vitaliusauleverx** [comment]
+
Have same issue. Sometimes it crashes on pitchEngine.stop() func.
